In [2]:
import numpy as np

def generate_part_names(num_parts): 
    return [chr(i) for i in range(ord('A'), ord('A') + num_parts)]

def input_transition_matrix(num_parts): 
    transition_matrix = [] 
    print("전이 행렬을 입력하세요. (예: 0 1 1 0)") 
    for i in range(num_parts): 
        row = list(map(int, input(f"{generate_part_names(num_parts)[i]}: ").split())) 
        transition_matrix.append(row) 
    return np.array(transition_matrix)

def main():
    num_parts = int(input("부품 수를 입력하세요: "))
    part_names = generate_part_names(num_parts)
    print("부품 이름:", part_names)
    
    transition_matrix = input_transition_matrix(num_parts)
    print("전이 행렬:")
    print(transition_matrix)
    
    part_rows = {}
    for i, part_name in enumerate(part_names):
        part_rows[part_name] = transition_matrix[i, :].tolist()
        
    print("부품 이름에 대한 전이 행렬 행:")
    print(part_rows)

    subassemblies = []
    for i in range(num_parts):
        subassemblies.append(part_names[i])
    for i in range(num_parts):
        for j in range(i+1, num_parts):
            if part_rows[part_names[i]][j] == 1:
                subassemblies.append(part_names[i] + part_names[j])
                for k in range(j+1, num_parts):
                    if part_rows[part_names[j]][k] == 1:
                        subassemblies.append(part_names[i] + part_names[j] + part_names[k])
                        for l in range(k+1, num_parts):
                            if part_rows[part_names[k]][l] == 1:
                                subassemblies.append(part_names[i] + part_names[j] + part_names[k] + part_names[l])
                                for m in range(l+1, num_parts):
                                    if part_rows[part_names[l]][m] == 1:
                                        subassemblies.append(part_names[i] + part_names[j] + part_names[k] + part_names[l] + part_names[m])

    subassemblies = sorted(subassemblies, key=len)
    print("Subassemblies for every level:")
    print(subassemblies)

    new_subassemblies = []
    for i in subassemblies:
        if len(i) > 1:
            new_subassemblies.append(i)

    new_subassemblies.insert(0, part_names)
    print("New Subassemblies:")
    print(new_subassemblies)

    new_subassemblies[0] = 'A'

    # Add a dictionary to map the new subassembly names to indices
    index_map = {tuple(name): i for i, name in enumerate(new_subassemblies)}

    matrix = np.zeros((len(new_subassemblies), len(new_subassemblies)), dtype=int)

    # Update the matrix based on the presence of elements in the new subassemblies
    for i, subassembly_row in enumerate(new_subassemblies):
        for j, subassembly_col in enumerate(new_subassemblies):
            if i != j:
                if (len(subassembly_row) == 1 and len(subassembly_row) + 1 == len(subassembly_col)) or (len(subassembly_row) > 1 and len(subassembly_row) + 1 == len(subassembly_col) and all(part in subassembly_col for part in subassembly_row)):
                    matrix[i, j] = 1

    # Print the final matrix
    print("Matrix with numbers based on element presence:")
    print(np.array(matrix))

    # Print the matrix with subassembly names
    print("Matrix with subassembly names:")
    print("\t" + "\t".join(map(str, new_subassemblies)))
    for i, row in enumerate(matrix):
        print(str(new_subassemblies[i]) + "\t" + "\t".join(map(str, row.tolist())))

if __name__ == "__main__":
    main()


부품 이름: ['A', 'B', 'C', 'D']
전이 행렬을 입력하세요. (예: 0 1 1 0)
전이 행렬:
[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
부품 이름에 대한 전이 행렬 행:
{'A': [0, 1, 1, 0], 'B': [0, 0, 1, 0], 'C': [0, 0, 0, 1], 'D': [0, 0, 0, 0]}
Subassemblies for every level:
['A', 'B', 'C', 'D', 'AB', 'AC', 'BC', 'CD', 'ABC', 'ACD', 'BCD', 'ABCD']
New Subassemblies:
[['A', 'B', 'C', 'D'], 'AB', 'AC', 'BC', 'CD', 'ABC', 'ACD', 'BCD', 'ABCD']
Matrix with numbers based on element presence:
[[0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]]
Matrix with subassembly names:
	A	AB	AC	BC	CD	ABC	ACD	BCD	ABCD
A	0	1	1	1	1	0	0	0	0
AB	0	0	0	0	0	1	0	0	0
AC	0	0	0	0	0	1	1	0	0
BC	0	0	0	0	0	1	0	1	0
CD	0	0	0	0	0	0	1	1	0
ABC	0	0	0	0	0	0	0	0	1
ACD	0	0	0	0	0	0	0	0	1
BCD	0	0	0	0	0	0	0	0	1
ABCD	0	0	0	0	0	0	0	0	0
